# GitHub Sponsors
github: v-code01

# Open Collective
open_collective: edgetrain

# Ko-fi
ko_fi: edgetrain

# Patreon
patreon: edgetrain

# Custom
custom: ["https://paypal.me/edgetrain", "https://edgetrain.dev/sponsor"]